@BASE_URL = http://localhost:8081

## Get books
GET {{BASE_URL}}/books

### Add a new book
POST {{BASE_URL}}/books
Content-Type: application/json

{
  "title": "The Lord of the Rings",
  "author": "J.R.R. Tolkien",
  "genre": "Fantasy"
}